import { createFileRoute } from "@tanstack/react-router";
import { breadcrumbLd, jsonLdScript, pageMeta } from "@/lib/site";
import { SiteLayout, Breadcrumbs } from "@/components/SiteLayout";
import { BundleCalculator } from "@/components/BundleCalculator";
import { Link } from "@tanstack/react-router";

const title = "Contractor Resources — Western Red Cedar Shingles for Siding Projects";
const description = "Spec sheet, bulk ordering info, installation reference, and client-facing talking points for contractors and remodelers using Western Red Cedar Shingles from Lowe's.";

export const Route = createFileRoute("/contractor-resources")({
  head: () => ({ ...pageMeta({ title, description, path: "/contractor-resources" }), scripts: [jsonLdScript({ "@context": "https://schema.org", "@type": "Service", name: "Western Red Cedar Shingles Contractor Resources", description }), jsonLdScript(breadcrumbLd([{ name: "Home", path: "/" }, { name: "Contractor Resources", path: "/contractor-resources" }]))] }),
  component: ContractorResourcesPage,
});

const specs = [["Grade", "#3/#4 undercourse (utility grade)"], ["Coverage", "15 sq ft per bundle at 7.5 inch exposure"], ["Fasteners", "Type 304 or 316 stainless-steel ring-shank nails for exterior installs"], ["Item number", "#3976 / Model #3976"], ["Retail price", "$50 per bundle"], ["Available", "Lowe's in-store only, no minimum order"]];

function ContractorResourcesPage() {
  return <SiteLayout><div className="mx-auto max-w-4xl px-4 py-12 sm:px-6"><Breadcrumbs items={[{ name: "Home", path: "/" }, { name: "Contractor Resources" }]} /><h1 className="font-display mt-8 text-5xl font-bold text-primary">Contractor Resources</h1><p className="font-body mt-5 text-lg text-foreground/80">Real cedar character at a price that keeps bids competitive. Here is what you need to spec, order, and install Western Red Cedar Shingles on a client project.</p><h2 className="font-display mt-14 text-3xl font-bold text-primary">Why Contractors Choose This Product</h2><p className="font-body mt-4 text-foreground/80">Our #3/#4 grade delivers the look clients want: real cedar, natural knots and grain, at a price point premium grades cannot match. It is an easy upsell on sheds, privacy screens, and accent walls, and a distinctive, affordable siding alternative on full exteriors.</p><h2 className="font-display mt-14 text-3xl font-bold text-primary">Bulk Ordering and Pro Desk</h2><p className="font-body mt-4 text-foreground/80">Western Red Cedar Shingles are available in bulk through the Pro Desk at any stocking Lowe's location. The Pro Desk can also special order at non-stocking stores.</p><Link to="/store-locator" className="font-ui mt-5 inline-block font-semibold text-accent">Find a Stocking Location →</Link><h2 className="font-display mt-14 text-3xl font-bold text-primary">Spec Sheet</h2><dl className="mt-6 overflow-hidden rounded-lg border border-border bg-card">{specs.map(([term,value]) => <div key={term} className="grid border-b border-border p-4 last:border-0 sm:grid-cols-[180px_1fr]"><dt className="font-ui font-semibold text-primary">{term}</dt><dd className="font-body text-foreground/80">{value}</dd></div>)}</dl><a href="/images/wrc-spec-sheet.pdf" className="font-ui mt-5 inline-block font-semibold text-accent">Download our one-page PDF spec sheet →</a><div className="mt-10"><BundleCalculator /></div><h2 className="font-display mt-14 text-3xl font-bold text-primary">Installation Reference</h2><Link to="/installation-guide" className="font-ui mt-4 inline-block font-semibold text-accent">View the Installation Guide →</Link><h2 className="font-display mt-14 text-3xl font-bold text-primary">Questions</h2><p className="font-body mt-4 text-foreground/80">Questions on volume pricing or availability? Ask your local Lowe's pro desk directly.</p><Link to="/store-locator" className="font-ui mt-4 inline-block font-semibold text-accent">Find your nearest pro desk →</Link></div></SiteLayout>;
}